import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        
      <table border="1">
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Role</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>user1</td>
      <td>user1</td>
      <td>User</td>
    </tr>
    <tr>
      <td>admin1</td>
      <td>admin1</td>
      <td>Admin</td>
    </tr>
    <tr>
      <td>owner1</td>
      <td>owner1</td>
      <td>Owner</td>
    </tr>
  </tbody>
</table>

        {/* Header content */}
      </main>
    </>
  );
}
